Repository AY2122S2-CS2103-W17-4/tp, pull requests merged in 2022-04, with the labels that each got.

#203 Update UserGuide for Positions
  docs/UserGuide.md
Labels: type.Chore

#268 Fix `edit interview`
  src/main/java/seedu/address/logic/commands/interview/EditInterviewCommand.java
Labels: type.Bug, severity.Medium

#271 Make command result text box wrap instead of scroll bar
  src/main/resources/view/ResultDisplay.fxml
Labels: severity.VeryLow

#272 Update user guide according to PE-D comments
  docs/UserGuide.md
Labels: severity.Low

#267 Make status badge stay on top when resizing window
  src/main/resources/view/ApplicantListCard.fxml
  src/main/resources/view/InterviewListCard.fxml
Labels: type.Bug, severity.VeryLow

#273 Add unit tests for the following classes
  src/main/java/seedu/address/logic/commands/position/DeletePositionCommand.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/commands/applicant/AddApplicantCommandTest.java
  src/test/java/seedu/address/logic/commands/position/AddPositionCommandTest.java
  src/test/java/seedu/address/logic/parser/position/DeletePositionCommandParserTest.java
  src/test/java/seedu/address/logic/parser/position/EditPositionCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPositionDescriptorBuilder.java
Labels: priority.High

#282 Update UserGuide to reflect proper usage for Positions
  docs/UserGuide.md
Labels: severity.High

#283 Change UI style
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/position/ListPositionCommand.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.Low

#287 Fix errors from changing person to applicant
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: severity.High

#286 Fix bug report from PE-D
  docs/UserGuide.md
  src/main/java/seedu/address/commons/exceptions/ExportCsvOpenException.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/ExportCsvCommand.java
  src/main/java/seedu/address/logic/commands/applicant/ExportApplicantCsvCommand.java
  src/main/java/seedu/address/logic/commands/help/DetailHelpCommand.java
  src/main/java/seedu/address/logic/commands/help/HelpDescription.java
  src/main/java/seedu/address/logic/commands/interview/ExportInterviewCsvCommand.java
  src/main/java/seedu/address/logic/commands/position/ExportPositionCsvCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/applicant/Phone.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
Labels: priority.High, type.Bug, severity.High

#297 Update PPP for Khoa
  docs/team/khoahre123.md
Labels: priority.High

#302 Fix bug related to parsing empty requirement
  src/main/java/seedu/address/logic/parser/position/EditPositionCommandParser.java
Labels: priority.High, severity.High

#300 Update name of logging file created
  src/main/java/seedu/address/commons/core/LogsCenter.java
Labels: severity.Low

#303 281 add unit tests position command
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/position/PositionOpenings.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/applicant/EditApplicantCommandTest.java
  src/test/java/seedu/address/logic/commands/position/DeletePositionCommandTest.java
  src/test/java/seedu/address/logic/commands/position/EditPositionCommandTest.java
  src/test/java/seedu/address/logic/commands/position/EditPositionDescriptorTest.java
  src/test/java/seedu/address/testutil/EditApplicantDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalAddressBook.java
Labels: priority.Medium

#306 Update DG to reflect accurate sequence diagram & Position implementation
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  src/main/java/seedu/address/logic/HelpArgument.java
Labels: priority.Medium

#315 refactor AddressBook to HireLah
  docs/diagrams/ArchitectureSequenceDiagram.puml
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/parser/HireLahParser.java
  src/main/java/seedu/address/model/HireLah.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyHireLah.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/HireLahStorage.java
  src/main/java/seedu/address/storage/JsonHireLahStorage.java
  src/main/java/seedu/address/storage/JsonSerializableHireLah.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/ApplicantCard.java
  src/main/java/seedu/address/ui/InterviewCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PositionCard.java
  src/test/data/JsonHireLahStorageTest/invalidAndValidApplicantHireLah.json
  src/test/data/JsonHireLahStorageTest/invalidApplicantHireLah.json
  src/test/data/JsonHireLahStorageTest/notJsonFormatHireLah.json
  src/test/data/JsonSerializableHireLahTest/duplicateApplicantHireLah.json
  src/test/data/JsonSerializableHireLahTest/invalidApplicantHireLah.json
  src/test/data/JsonSerializableHireLahTest/typicalApplicantsHireLah.json
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/commands/applicant/AddApplicantCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/applicant/AddApplicantCommandTest.java
  src/test/java/seedu/address/logic/commands/applicant/DeleteApplicantCommandTest.java
  src/test/java/seedu/address/logic/commands/applicant/EditApplicantCommandTest.java
  src/test/java/seedu/address/logic/commands/applicant/ListApplicantCommandTest.java
  src/test/java/seedu/address/logic/commands/interview/DeleteInterviewCommandTest.java
  src/test/java/seedu/address/logic/commands/position/AddPositionCommandTest.java
  src/test/java/seedu/address/logic/commands/position/DeletePositionCommandTest.java
  src/test/java/seedu/address/logic/commands/position/EditPositionCommandTest.java
  src/test/java/seedu/address/logic/parser/applicant/HireLahParserTest.java
  src/test/java/seedu/address/model/HireLahTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/storage/JsonHireLahStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableHireLahTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/HireLahBuilder.java
  src/test/java/seedu/address/testutil/TypicalHireLah.java
Labels: priority.Medium, type.Chore

#314 Update sorting part in DG
  docs/DeveloperGuide.md
Labels: priority.High

#346 Check if applicant is hired when adding/editing interview
  src/main/java/seedu/address/logic/commands/interview/EditInterviewCommand.java
Labels: severity.High

#360 Add export dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/SortSequenceDiagram.png
  src/main/java/seedu/address/logic/HelpArgument.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.High

#368 Update Khoa PPP
  docs/team/khoahre123.md
  src/main/java/seedu/address/model/applicant/Applicant.java
  src/main/java/seedu/address/model/position/Position.java
Labels: priority.High

#371 Update DG for use cases
  docs/DeveloperGuide.md
Labels: priority.High
