Repository AY2122S2-CS2103-W17-4/tp, pull requests merged in 2022-03, with the labels that each got.

#15 5 update about us weihowe
  docs/AboutUs.md
  docs/images/goalfix.png
  docs/team/goalfix.md
Labels: documentation

#16 Add interview section in user guide
  docs/UserGuide.md
Labels: documentation

#21 Update description for Yi Hern in AboutUs page
  docs/AboutUs.md
  docs/images/yihern-lee.png
Labels: documentation

#22 Add skeleton PPP to update Yi Hern's future contributions
  docs/team/yihern-lee.md
Labels: documentation

#50 Edit `edit` commands in UserGuide.md
  docs/UserGuide.md
Labels: priority.High

#52 Fix user guide according with change in delete syntax
  docs/UserGuide.md
Labels: priority.High

#59 Fix list command in user guide according to new syntax
  docs/UserGuide.md
Labels: priority.High

#58 Refactor command parser
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/core/TypeFlags.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/applicants/AddApplicantCommandParser.java
  src/main/java/seedu/address/logic/parser/applicants/DeleteApplicantCommandParser.java
  src/main/java/seedu/address/logic/parser/applicants/EditApplicantCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddApplicantCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteApplicantCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditApplicantCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#66 Make AddCommand, DeleteCommand, and ListCommand abstract
  src/main/java/seedu/address/logic/commands/add/AddApplicantCommand.java
  src/main/java/seedu/address/logic/commands/add/AddCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteApplicantCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/list/ListApplicantCommand.java
  src/main/java/seedu/address/logic/commands/list/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/applicants/AddApplicantCommandParser.java
  src/main/java/seedu/address/logic/parser/applicants/DeleteApplicantCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddApplicantCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddApplicantCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteApplicantCommandTest.java
  src/test/java/seedu/address/logic/commands/ListApplicantCommandTest.java
  src/test/java/seedu/address/logic/parser/AddApplicantCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteApplicantCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#69 Add Position package and classes into Model
  src/main/java/seedu/address/model/position/Description.java
  src/main/java/seedu/address/model/position/Position.java
  src/main/java/seedu/address/model/position/PositionName.java
  src/main/java/seedu/address/model/position/PositionOpenings.java
  src/main/java/seedu/address/model/position/Requirement.java
  src/main/java/seedu/address/model/position/UniquePositionList.java
  src/main/java/seedu/address/model/position/exceptions/DuplicatePositionException.java
  src/main/java/seedu/address/model/position/exceptions/PositionNotFoundException.java
Labels: priority.High

#72 Add unit tests for position package
  src/main/java/seedu/address/model/position/Description.java
  src/main/java/seedu/address/model/position/PositionName.java
  src/main/java/seedu/address/model/position/Requirement.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/position/DescriptionTest.java
  src/test/java/seedu/address/model/position/PositionNameTest.java
  src/test/java/seedu/address/model/position/PositionOpeningsTest.java
  src/test/java/seedu/address/model/position/PositionTest.java
  src/test/java/seedu/address/model/position/RequirementTest.java
  src/test/java/seedu/address/testutil/PositionBuilder.java
  src/test/java/seedu/address/testutil/TypicalPositions.java
Labels: priority.High

#73 Add UniquePositionList to AddressBook
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/test/java/seedu/address/logic/commands/AddApplicantCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.High

#83 Add tabs with positions and interviews list to the UI
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/ui/ApplicantCard.java
  src/main/java/seedu/address/ui/ApplicantListPanel.java
  src/main/java/seedu/address/ui/InterviewCard.java
  src/main/java/seedu/address/ui/InterviewListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/PositionCard.java
  src/main/java/seedu/address/ui/PositionListPanel.java
  src/main/resources/view/ApplicantListCard.fxml
  src/main/resources/view/ApplicantListPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InterviewListCard.fxml
  src/main/resources/view/InterviewListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/PositionListCard.fxml
  src/main/resources/view/PositionListPanel.fxml
Labels: priority.High

#87 Update the applicant constructor for sample interview data
  src/main/java/seedu/address/ui/InterviewListPanel.java
Labels: type.Bug, severity.High

#88 fix MESSAGE_USAGE string in AddApplicantCommand Class
  src/main/java/seedu/address/logic/commands/add/AddApplicantCommand.java
Labels: type.Bug, severity.Medium

#90 Integrate Position list in AddressBook with UI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteApplicantCommand.java
  src/main/java/seedu/address/logic/commands/interview/AddInterviewCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/position/UniquePositionList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PositionListPanel.java
  src/test/java/seedu/address/logic/commands/AddApplicantCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteApplicantCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
Labels: priority.High, type.Bug

#94 Add support for tab change on command
  src/main/java/seedu/address/commons/core/DataType.java
  src/main/java/seedu/address/commons/core/DataTypeFlags.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/add/AddApplicantCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteApplicantCommand.java
  src/main/java/seedu/address/logic/commands/help/DetailHelpCommand.java
  src/main/java/seedu/address/logic/commands/help/OverallHelpCommand.java
  src/main/java/seedu/address/logic/commands/interview/AddInterviewCommand.java
  src/main/java/seedu/address/logic/commands/list/ListApplicantCommand.java
  src/main/java/seedu/address/logic/commands/position/AddPositionCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddApplicantCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: priority.Medium

#96 Link applicant gender age
  src/main/java/seedu/address/ui/ApplicantCard.java
  src/main/resources/view/ApplicantListCard.fxml
  src/main/resources/view/DarkTheme.css
Labels: priority.Medium

#105 Organise the folders in commands
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/applicant/AddApplicantCommand.java
  src/main/java/seedu/address/logic/commands/applicant/DeleteApplicantCommand.java
  src/main/java/seedu/address/logic/commands/applicant/ListApplicantCommand.java
  src/main/java/seedu/address/logic/commands/interview/AddInterviewCommand.java
  src/main/java/seedu/address/logic/commands/position/AddPositionCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/applicants/AddApplicantCommandParser.java
  src/main/java/seedu/address/logic/parser/applicants/DeleteApplicantCommandParser.java
  src/main/java/seedu/address/ui/InterviewCard.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddApplicantCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddApplicantCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteApplicantCommandTest.java
  src/test/java/seedu/address/logic/commands/ListApplicantCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteApplicantCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.Medium

#113 Add support for DeleteCommand
  src/main/java/seedu/address/logic/commands/position/DeletePositionCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/position/DeletePositionCommandParser.java
Labels: priority.High

#104 Refactor UniquePersonList to UniqueApplicantList
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/applicant/UniqueApplicantList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddApplicantCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/DeleteApplicantCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddApplicantCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/applicant/UniqueApplicantListTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium, type.Chore

#120 Add unit tests for AddPositionCommandParser
  src/main/java/seedu/address/logic/parser/position/AddPositionCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/position/AddPositionCommandParserTest.java
  src/test/java/seedu/address/testutil/PositionBuilder.java
  src/test/java/seedu/address/testutil/PositionUtil.java
Labels: priority.High, type.Chore

#132 Add support for keep track of job offers in Position
  src/main/java/seedu/address/model/Counter.java
  src/main/java/seedu/address/model/position/Position.java
  src/main/java/seedu/address/model/position/PositionOffers.java
  src/main/java/seedu/address/model/position/PositionOpenings.java
  src/main/java/seedu/address/ui/PositionCard.java
  src/test/java/seedu/address/model/position/PositionTest.java
  src/test/java/seedu/address/testutil/PositionUtil.java
Labels: priority.High

#131 Refactor edit command
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/applicant/EditApplicantCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/applicants/EditApplicantCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditApplicantCommandTest.java
  src/test/java/seedu/address/logic/commands/EditApplicantDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditApplicantCommandParserTest.java
  src/test/java/seedu/address/testutil/ApplicantUtil.java
  src/test/java/seedu/address/testutil/EditApplicantDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: priority.High

#137 Add support for editing Positions
  src/main/java/seedu/address/logic/commands/position/AddPositionCommand.java
  src/main/java/seedu/address/logic/commands/position/EditPositionCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/position/EditPositionCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/position/Position.java
  src/test/java/seedu/address/logic/commands/AddApplicantCommandTest.java
Labels: priority.High

#138 Fix unable to parse requirements bug
  src/main/java/seedu/address/logic/parser/position/EditPositionCommandParser.java
Labels: type.Bug

#139 Display offered and interviewstatus
  src/main/java/seedu/address/ui/InterviewCard.java
  src/main/java/seedu/address/ui/PositionCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InterviewListCard.fxml
  src/main/resources/view/PositionListCard.fxml
Labels: priority.Medium

#140 Cascade delete for applicant and position to delete related interviews
  src/main/java/seedu/address/logic/commands/applicant/DeleteApplicantCommand.java
  src/main/java/seedu/address/logic/commands/position/DeletePositionCommand.java
  src/main/java/seedu/address/model/interview/Interview.java
  src/test/java/seedu/address/logic/commands/DeleteApplicantCommandTest.java
Labels: severity.High

#144 Add logging for add command parser
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: priority.Medium, type.Chore

#145 Add logging to record information of deleted interview from cascading
  src/main/java/seedu/address/logic/commands/applicant/DeleteApplicantCommand.java
  src/main/java/seedu/address/logic/commands/position/DeletePositionCommand.java
Labels: priority.Medium, type.Chore

#143 Add edit feature for interview
  src/main/java/seedu/address/logic/commands/applicant/EditApplicantCommand.java
  src/main/java/seedu/address/logic/commands/interview/EditInterviewCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/interview/EditInterviewCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/logic/commands/AddApplicantCommandTest.java
Labels: priority.Medium

#150 Update DeveloperGuide to include steps for editing position
  docs/DeveloperGuide.md
Labels: type.Chore

#154 Implement filter feature for list command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/FilterArgument.java
  src/main/java/seedu/address/logic/FilterType.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/applicant/EditApplicantCommand.java
  src/main/java/seedu/address/logic/commands/applicant/ListApplicantCommand.java
  src/main/java/seedu/address/logic/commands/interview/ListInterviewCommand.java
  src/main/java/seedu/address/logic/commands/position/ListPositionCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/applicants/ListApplicantCommandParser.java
  src/main/java/seedu/address/logic/parser/interview/ListInterviewCommandParser.java
  src/main/java/seedu/address/logic/parser/position/ListPositionCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/applicant/ApplicantNamePredicate.java
  src/main/java/seedu/address/model/interview/InterviewApplicantPredicate.java
  src/main/java/seedu/address/model/interview/InterviewDatePredicate.java
  src/main/java/seedu/address/model/interview/InterviewPositionPredicate.java
  src/main/java/seedu/address/model/position/PositionNamePredicate.java
  src/test/java/seedu/address/logic/commands/AddApplicantCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteApplicantCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListApplicantCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/applicant/ApplicantNamePredicateTest.java
Labels: priority.Medium

#164 Add support for cascading effects of editing Position and Applicant
  src/main/java/seedu/address/logic/commands/applicant/EditApplicantCommand.java
  src/main/java/seedu/address/logic/commands/position/EditPositionCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/interview/UniqueInterviewList.java
  src/test/java/seedu/address/logic/commands/applicant/AddApplicantCommandTest.java
Labels: priority.High, severity.High

#167 Add support for maintaining immutability of Position objects
  src/main/java/seedu/address/model/ImmutableCounter.java
  src/main/java/seedu/address/model/position/Position.java
  src/main/java/seedu/address/model/position/PositionOffers.java
  src/main/java/seedu/address/model/position/PositionOpenings.java
  src/main/java/seedu/address/model/position/exceptions/UnableToAcceptOfferException.java
  src/main/java/seedu/address/model/position/exceptions/UnableToExtendOfferException.java
  src/main/java/seedu/address/model/position/exceptions/UnableToRejectOfferException.java
  src/test/java/seedu/address/model/position/PositionTest.java
Labels: priority.High

#170 Display applicant's hired status in UI
  src/main/java/seedu/address/ui/ApplicantCard.java
  src/main/resources/view/ApplicantListCard.fxml
  src/main/resources/view/DarkTheme.css
Labels: priority.High

#171 Update storage for interview to include composition
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/applicant/UniqueApplicantList.java
  src/main/java/seedu/address/model/interview/Interview.java
  src/main/java/seedu/address/model/position/UniquePositionList.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: priority.High

#168 Press up/down arrows to get previous commands
  src/main/java/seedu/address/ui/CommandBox.java
Labels: priority.Medium

#169 Check for duplicate email and phone when adding/editing an applicant
  src/main/java/seedu/address/logic/commands/applicant/AddApplicantCommand.java
  src/main/java/seedu/address/logic/commands/applicant/EditApplicantCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/applicant/UniqueApplicantList.java
  src/test/java/seedu/address/logic/commands/applicant/AddApplicantCommandTest.java
Labels: severity.Medium

#158 Implement sort list for applicant
  src/main/java/seedu/address/logic/SortArgument.java
  src/main/java/seedu/address/logic/commands/applicant/ListApplicantCommand.java
  src/main/java/seedu/address/logic/commands/interview/ListInterviewCommand.java
  src/main/java/seedu/address/logic/commands/position/ListPositionCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/GenericListParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/applicants/ListApplicantCommandParser.java
  src/main/java/seedu/address/logic/parser/interview/ListInterviewCommandParser.java
  src/main/java/seedu/address/logic/parser/position/ListPositionCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/applicant/ApplicantNameComparator.java
  src/main/java/seedu/address/model/applicant/UniqueApplicantList.java
  src/main/java/seedu/address/model/interview/Interview.java
  src/main/java/seedu/address/model/interview/InterviewDateComparator.java
  src/main/java/seedu/address/model/interview/Status.java
  src/main/java/seedu/address/model/interview/UniqueInterviewList.java
  src/main/java/seedu/address/model/position/PositionNameComparator.java
  src/main/java/seedu/address/model/position/UniquePositionList.java
  src/main/java/seedu/address/storage/JsonAdaptedInterview.java
  src/test/java/seedu/address/logic/commands/applicant/AddApplicantCommandTest.java
Labels: priority.Medium

#175 Add formatter for interview date in toString()
  src/main/java/seedu/address/model/interview/Interview.java
Labels: severity.Low

#173 Update applicant, interview and position support for storage
  src/main/java/seedu/address/model/position/PositionOffers.java
  src/main/java/seedu/address/storage/JsonAdaptedApplicant.java
  src/main/java/seedu/address/storage/JsonAdaptedInterview.java
  src/main/java/seedu/address/storage/JsonAdaptedPosition.java
Labels: priority.High, type.Chore

#186 Change interview status badge colour
  src/main/java/seedu/address/ui/InterviewCard.java
  src/main/resources/view/ApplicantListCard.fxml
Labels: severity.VeryLow

#188 Prevent toggling of interview status between pass and fail
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/interview/AcceptInterviewCommand.java
  src/main/java/seedu/address/logic/commands/interview/FailInterviewCommand.java
  src/main/java/seedu/address/logic/commands/interview/PassInterviewCommand.java
  src/main/java/seedu/address/logic/commands/interview/RejectInterviewCommand.java
  src/main/java/seedu/address/model/interview/Interview.java
  src/main/java/seedu/address/model/interview/Status.java
Labels: priority.High, type.Bug

#192 Fix Json storage parser problem
  .gitignore
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/goalfix.md
  docs/team/sethckl.md
  docs/team/yihern-lee.md
  src/main/java/seedu/address/storage/JsonAdaptedInterview.java
Labels: type.Bug, severity.High

#196 Check if applicant already has an interview for position
  src/main/java/seedu/address/logic/commands/interview/AddInterviewCommand.java
  src/main/java/seedu/address/logic/commands/interview/EditInterviewCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/interview/UniqueInterviewList.java
  src/test/java/seedu/address/logic/commands/applicant/AddApplicantCommandTest.java
Labels: severity.High

#191 Export csv for applicant, interview and position
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/ExportCsvCommand.java
  src/main/java/seedu/address/logic/commands/applicant/ExportApplicantCsvCommand.java
  src/main/java/seedu/address/logic/commands/interview/ExportInterviewCsvCommand.java
  src/main/java/seedu/address/logic/commands/position/ExportPositionCsvCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExportCsvCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/applicant/Applicant.java
  src/main/java/seedu/address/model/applicant/HiredStatus.java
  src/main/java/seedu/address/model/interview/Interview.java
  src/main/java/seedu/address/model/position/Position.java
  src/main/java/seedu/address/storage/JsonAdaptedApplicant.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/applicant/AddApplicantCommandTest.java
Labels: priority.Medium, type.Chore

#197 Add support for tags to have white spaces and other characters
  src/main/java/seedu/address/model/position/Requirement.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High

#195 Validate user input for sort argument
  docs/UserGuide.md
  src/main/java/seedu/address/logic/SortArgument.java
  src/main/java/seedu/address/logic/commands/applicant/ListApplicantCommand.java
  src/main/java/seedu/address/logic/commands/interview/ListInterviewCommand.java
  src/main/java/seedu/address/logic/commands/position/ListPositionCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/applicants/ListApplicantCommandParser.java
  src/main/java/seedu/address/logic/parser/position/ListPositionCommandParser.java
Labels: severity.Medium

#187 Add more filters
  docs/UserGuide.md
  src/main/java/seedu/address/logic/FilterType.java
  src/main/java/seedu/address/logic/commands/applicant/ListApplicantCommand.java
  src/main/java/seedu/address/logic/commands/interview/ListInterviewCommand.java
  src/main/java/seedu/address/logic/commands/position/ListPositionCommand.java
  src/main/java/seedu/address/logic/parser/applicants/ListApplicantCommandParser.java
  src/main/java/seedu/address/logic/parser/interview/ListInterviewCommandParser.java
  src/main/java/seedu/address/logic/parser/position/ListPositionCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/applicant/ApplicantGenderPredicate.java
  src/main/java/seedu/address/model/applicant/ApplicantStatusPredicate.java
  src/main/java/seedu/address/model/applicant/ApplicantTagPredicate.java
  src/main/java/seedu/address/model/interview/InterviewStatusPredicate.java
  src/main/java/seedu/address/model/position/PositionRequirementPredicate.java
Labels: priority.Medium

#199 Update user guide to include export
  docs/UserGuide.md
Labels: type.Chore

#200 Issue #198 Update fields in Applicant and Position to restrict length
  src/main/java/seedu/address/model/applicant/Address.java
  src/main/java/seedu/address/model/applicant/Age.java
  src/main/java/seedu/address/model/applicant/Email.java
  src/main/java/seedu/address/model/applicant/Name.java
  src/main/java/seedu/address/model/applicant/Phone.java
  src/main/java/seedu/address/model/position/Description.java
  src/main/java/seedu/address/model/position/PositionName.java
  src/main/java/seedu/address/model/position/PositionOpenings.java
  src/main/java/seedu/address/model/position/Requirement.java
  src/test/java/seedu/address/model/applicant/NameTest.java
Labels: priority.High
